### PR TITLE
ec2_events refactor

### PR DESCRIPTION
**Pull request by hanpeter**
1. Moved the `ec2_events.py` file into its own directory. (The file itself stays the same)
1. Refactored the `ec2_events.Application` as a separate `cli.py` and `ec2_event_checker.py` files.
1. Improved `ec2_event_checker.py` to utilize the [Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern).

### CODE REVIEW

**Comment by dcrampton** [comment]
Nothing stands out to me, but you'll want more eyeballs on it.

**Comment by plathrop** [comment]
+1

**Comment by paul-krohn** [comment]
You'll want a version bump?

**Comment by hanpeter** [comment]
@paul-krohn There is a part 2 of this. I'll add the version bump there.

**Pull request merged**
