### PR TITLE
W-8922370 vulnerability updates

### PR DESCRIPTION
**Pull request by instantlinux**
## What does this PR do?
_Adds Pipfile and eliminates vulnerability and license violations reported by snyk: pyyaml 5.2, sphinx 2.3.1, argh 0.26.2, jinja2 2.10.3, certifi / requests 2.22.0, pyflowdock 0.3.35, chardet._

## Why is this change being made?

[W-8922370](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097DrFIAU/view)

## How is it tested?

_See CI test run under `Details` below: 10 out of 10 tests passed; manual testing:_
```
$ pipenv run python3 -m aws_analysis_tools.cli.volumes -h
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Usage: volumes.py [options]

Options:
  -h, --help            show this help message and exit
  -v, --verbose         enable debug output
  -H, --no-header       suppress table header
  -i, --instance-name   Show instance names in attachment info (SLOW!)
  -r REGION, --region=REGION
                        ec2 region to connect to
  -n NAME, --name=NAME  Include volumes with these names only (regex)
  -N EXCLUDE_NAME, --exclude-name=EXCLUDE_NAME
                        Exclude volumes with these names (regex)
  -z ZONE, --zone=ZONE  Include volumes with these zones only (regex)
  -Z EXCLUDE_ZONE, --exclude-zone=EXCLUDE_ZONE
                        Exclude volumes with these zones (regex)
  -d DEVICE, --device=DEVICE
                        Include volumes attached to these devices only (regex)
  -D EXCLUDE_DEVICE, --exclude-device=EXCLUDE_DEVICE
                        Exclude volumes attached to these devices (regex)
```

## What gif best describes this PR or how it makes you feel?

python

## Completion checklist

- [x] The pull request has been appropriately labeled according to our
      [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review)
- [x] Stakeholders have been notified. Workflow-impacting changes have
      been appropriately socialized to avoid surprises.
- [x] The associated SOPKB entry has been updated along with relevant diagrams.
- [x] Linked this PR to the appropriate GUS ticket.

### CODE REVIEW

**Review by dllopis-sfdc — CHANGES_REQUESTED** [review]
IIRC correctly, you just need to put the offending package names in double quotes.

**Comment by pkrohn-sfdc** [comment]
Are we sure we use this package at all? I think Scott replaced it with a Puppet/Ruby library to manage tags.

**Comment by instantlinux** [comment]
> Are we sure we use this package at all? I think Scott replaced it with a Puppet/Ruby library to manage tags.

Idk. On the cc node, I see the command-line tools but -- may or may not have any users.
```
$ dpkg --list | grep aws-analysis
ii  aws-analysis-tools                0.6.6                                       amd64        no description given
$ dpkg -L aws-analysis-tools|tail 
/usr/local/aws-analysis-tools/lib/python3.6/LICENSE.txt
/usr/local/bin/krux-update-ec2-tags
/usr/local/bin/krux-ec2-ip
/usr/local/bin/krux-ec2-pssh
/usr/local/bin/krux-ec2-test-provision
/usr/local/bin/krux-ec2-instances
/usr/local/bin/krux-ec2-pssh2
/usr/local/bin/krux-search-ec2-tags
/usr/local/bin/krux-ec2-volumes
/usr/local/bin/krux-ec2-events
```

**Comment by instantlinux** [comment]
> IIRC correctly, you just need to put the offending package names in double quotes.

Whadya know, it works. Why didn't I thin of that? ;-) Done.

**Review by SFDC-AaronKulick — APPROVED** [review]

**Comment by SFDC-AaronKulick** [comment]
I approved this on the assertion that is needed per standup.

**Review by dllopis-sfdc — APPROVED** [review]

**Review by SFDC-AaronKulick — CHANGES_REQUESTED** [review]
Per standup I second that we should archive and remove the puppet code that manages the Chronos job.

**Comment by instantlinux** [comment]
Withdrawn as obsolete.

**Pull request closed without merging**
